/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video, FunctionLog,
HTTPRequest } from "@boundaryml/baml"
import { toBamlError, BamlStream, BamlAbortError, Collector } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {AlertLite, AnswerLines, ChatContext, ChatConversationMessage, ChatInterpretation, ChatSessionSummary, ConversationMessage, CurrentLite, DailyForecastItem, DailySummaryResult, EmailContext, EmailInterpretation, EnhancedQuery, FormattedWeather, HintCategory, HintEligibility, HintResult, LocationLite, MemoryContext, MemoryCore, MemorySynthesisLines, NewsItem, NoteContent, PlaceLines, PlaceSuggestion, QueryResult, QuestionAnalysisResponse, Router, RoutingBehavior, SessionInput, SessionSummaryOutput, TempBlock, WeatherConditionLite, WeatherLines} from "./types"
import type TypeBuilder from "./type_builder"
import { AsyncHttpRequest, AsyncHttpStreamRequest } from "./async_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"
import type * as events from "./events"

/**
* @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
*/
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>

    type TickReason = "Unknown";

    type BamlCallOptions<WatchersT = never> = {
    tb?: TypeBuilder
    clientRegistry?: ClientRegistry
    collector?: Collector | Collector[]
    env?: Record<string, string | undefined>
      tags?: Record<string, string>
        signal?: AbortSignal
        onTick?: (reason: TickReason, log: FunctionLog | null) => void
        watchers?: WatchersT
        }

        export class BamlAsyncClient {
        private runtime: BamlRuntime
        private ctxManager: BamlCtxManager
        private streamClient: BamlStreamClient
        private httpRequest: AsyncHttpRequest
        private httpStreamRequest: AsyncHttpStreamRequest
        private llmResponseParser: LlmResponseParser
        private llmStreamParser: LlmStreamParser
        private bamlOptions: BamlCallOptions

        constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
        this.runtime = runtime
        this.ctxManager = ctxManager
        this.streamClient = new BamlStreamClient(runtime, ctxManager, bamlOptions)
        this.httpRequest = new AsyncHttpRequest(runtime, ctxManager)
        this.httpStreamRequest = new AsyncHttpStreamRequest(runtime, ctxManager)
        this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
        this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
        this.bamlOptions = bamlOptions || {}
        }

        withOptions(bamlOptions: BamlCallOptions) {
        return new BamlAsyncClient(this.runtime, this.ctxManager, bamlOptions)
        }

        get stream() {
        return this.streamClient
        }

        get request() {
        return this.httpRequest
        }

        get streamRequest() {
        return this.httpStreamRequest
        }

        get parse() {
        return this.llmResponseParser
        }

        get parseStream() {
        return this.llmStreamParser
        }

        
        async AbridgeToNote(
        transcripts: string[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.NoteContent> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.AbridgeToNote(
          transcripts,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "AbridgeToNote",
            {
            "transcripts": transcripts
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.NoteContent
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async AnswerQuestion(
        text: string,memory?: types.MemoryCore | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.QuestionAnalysisResponse> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.AnswerQuestion(
          text,memory,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "AnswerQuestion",
            {
            "text": text,"memory": memory?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.QuestionAnalysisResponse
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async AnswerSearch(
        query: string,searchResults: types.NewsItem[],memory?: types.MemoryCore | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.QueryResult> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.AnswerSearch(
          query,searchResults,memory,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "AnswerSearch",
            {
            "query": query,"searchResults": searchResults,"memory": memory?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.QueryResult
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async ClassifyForHint(
        text: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.HintEligibility> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.ClassifyForHint(
          text,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "ClassifyForHint",
            {
            "text": text
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.HintEligibility
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async EnhanceQuery(
        query: string,memory?: types.MemoryCore | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.EnhancedQuery> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.EnhanceQuery(
          query,memory,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "EnhanceQuery",
            {
            "query": query,"memory": memory?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.EnhancedQuery
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async GenerateHint(
        topic: string,userSpeech: string,memory?: types.MemoryCore | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.HintResult> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.GenerateHint(
          topic,userSpeech,memory,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "GenerateHint",
            {
            "topic": topic,"userSpeech": userSpeech,"memory": memory?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.HintResult
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async InterpretChatMessage(
        userMessage: string,context: types.ChatContext,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.ChatInterpretation> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.InterpretChatMessage(
          userMessage,context,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "InterpretChatMessage",
            {
            "userMessage": userMessage,"context": context
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.ChatInterpretation
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async InterpretEmailReply(
        userMessage: string,context: types.EmailContext,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.EmailInterpretation> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.InterpretEmailReply(
          userMessage,context,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "InterpretEmailReply",
            {
            "userMessage": userMessage,"context": context
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.EmailInterpretation
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async Route(
        text: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.RoutingBehavior> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.Route(
          text,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "Route",
            {
            "text": text
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.RoutingBehavior
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async SummarizeDailySessions(
        sessions: types.SessionInput[],userProfile?: string | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.DailySummaryResult> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.SummarizeDailySessions(
          sessions,userProfile,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "SummarizeDailySessions",
            {
            "sessions": sessions,"userProfile": userProfile?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.DailySummaryResult
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async SummarizePlaces(
        query: string,places: types.PlaceSuggestion[],memory?: types.MemoryCore | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.PlaceLines> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.SummarizePlaces(
          query,places,memory,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "SummarizePlaces",
            {
            "query": query,"places": places,"memory": memory?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.PlaceLines
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async SummarizeSession(
        transcripts: string[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.SessionSummaryOutput> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.SummarizeSession(
          transcripts,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "SummarizeSession",
            {
            "transcripts": transcripts
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.SessionSummaryOutput
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async SummarizeWeatherFormatted(
        input: types.FormattedWeather,unit: string,memory?: types.MemoryCore | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.WeatherLines> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.SummarizeWeatherFormatted(
          input,unit,memory,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "SummarizeWeatherFormatted",
            {
            "input": input,"unit": unit,"memory": memory?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.WeatherLines
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async SynthesizeMemory(
        query: string,context: types.MemoryContext,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.MemorySynthesisLines> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.SynthesizeMemory(
          query,context,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const __raw__ = await this.runtime.callFunction(
            "SynthesizeMemory",
            {
            "query": query,"context": context
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __options__.clientRegistry,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.MemorySynthesisLines
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
            }

            class BamlStreamClient {
            private runtime: BamlRuntime
            private ctxManager: BamlCtxManager
            private bamlOptions: BamlCallOptions

            constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
            this.runtime = runtime
            this.ctxManager = ctxManager
            this.bamlOptions = bamlOptions || {}
            }

            
            AbridgeToNote(
            transcripts: string[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.NoteContent, types.NoteContent>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for AbridgeToNote", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "AbridgeToNote",
                {
                "transcripts": transcripts
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.NoteContent, types.NoteContent>(
                  __raw__,
                  (a): partial_types.NoteContent => a,
                  (a): types.NoteContent => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            AnswerQuestion(
            text: string,memory?: types.MemoryCore | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.QuestionAnalysisResponse, types.QuestionAnalysisResponse>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for AnswerQuestion", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "AnswerQuestion",
                {
                "text": text,"memory": memory ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.QuestionAnalysisResponse, types.QuestionAnalysisResponse>(
                  __raw__,
                  (a): partial_types.QuestionAnalysisResponse => a,
                  (a): types.QuestionAnalysisResponse => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            AnswerSearch(
            query: string,searchResults: types.NewsItem[],memory?: types.MemoryCore | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.QueryResult, types.QueryResult>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for AnswerSearch", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "AnswerSearch",
                {
                "query": query,"searchResults": searchResults,"memory": memory ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.QueryResult, types.QueryResult>(
                  __raw__,
                  (a): partial_types.QueryResult => a,
                  (a): types.QueryResult => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            ClassifyForHint(
            text: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.HintEligibility, types.HintEligibility>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for ClassifyForHint", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "ClassifyForHint",
                {
                "text": text
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.HintEligibility, types.HintEligibility>(
                  __raw__,
                  (a): partial_types.HintEligibility => a,
                  (a): types.HintEligibility => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            EnhanceQuery(
            query: string,memory?: types.MemoryCore | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.EnhancedQuery, types.EnhancedQuery>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for EnhanceQuery", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "EnhanceQuery",
                {
                "query": query,"memory": memory ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.EnhancedQuery, types.EnhancedQuery>(
                  __raw__,
                  (a): partial_types.EnhancedQuery => a,
                  (a): types.EnhancedQuery => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            GenerateHint(
            topic: string,userSpeech: string,memory?: types.MemoryCore | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.HintResult, types.HintResult>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for GenerateHint", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "GenerateHint",
                {
                "topic": topic,"userSpeech": userSpeech,"memory": memory ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.HintResult, types.HintResult>(
                  __raw__,
                  (a): partial_types.HintResult => a,
                  (a): types.HintResult => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            InterpretChatMessage(
            userMessage: string,context: types.ChatContext,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.ChatInterpretation, types.ChatInterpretation>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for InterpretChatMessage", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "InterpretChatMessage",
                {
                "userMessage": userMessage,"context": context
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.ChatInterpretation, types.ChatInterpretation>(
                  __raw__,
                  (a): partial_types.ChatInterpretation => a,
                  (a): types.ChatInterpretation => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            InterpretEmailReply(
            userMessage: string,context: types.EmailContext,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.EmailInterpretation, types.EmailInterpretation>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for InterpretEmailReply", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "InterpretEmailReply",
                {
                "userMessage": userMessage,"context": context
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.EmailInterpretation, types.EmailInterpretation>(
                  __raw__,
                  (a): partial_types.EmailInterpretation => a,
                  (a): types.EmailInterpretation => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            Route(
            text: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.RoutingBehavior, types.RoutingBehavior>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for Route", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "Route",
                {
                "text": text
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.RoutingBehavior, types.RoutingBehavior>(
                  __raw__,
                  (a): partial_types.RoutingBehavior => a,
                  (a): types.RoutingBehavior => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            SummarizeDailySessions(
            sessions: types.SessionInput[],userProfile?: string | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.DailySummaryResult, types.DailySummaryResult>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for SummarizeDailySessions", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "SummarizeDailySessions",
                {
                "sessions": sessions,"userProfile": userProfile ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.DailySummaryResult, types.DailySummaryResult>(
                  __raw__,
                  (a): partial_types.DailySummaryResult => a,
                  (a): types.DailySummaryResult => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            SummarizePlaces(
            query: string,places: types.PlaceSuggestion[],memory?: types.MemoryCore | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.PlaceLines, types.PlaceLines>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for SummarizePlaces", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "SummarizePlaces",
                {
                "query": query,"places": places,"memory": memory ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.PlaceLines, types.PlaceLines>(
                  __raw__,
                  (a): partial_types.PlaceLines => a,
                  (a): types.PlaceLines => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            SummarizeSession(
            transcripts: string[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.SessionSummaryOutput, types.SessionSummaryOutput>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for SummarizeSession", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "SummarizeSession",
                {
                "transcripts": transcripts
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.SessionSummaryOutput, types.SessionSummaryOutput>(
                  __raw__,
                  (a): partial_types.SessionSummaryOutput => a,
                  (a): types.SessionSummaryOutput => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            SummarizeWeatherFormatted(
            input: types.FormattedWeather,unit: string,memory?: types.MemoryCore | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.WeatherLines, types.WeatherLines>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for SummarizeWeatherFormatted", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "SummarizeWeatherFormatted",
                {
                "input": input,"unit": unit,"memory": memory ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.WeatherLines, types.WeatherLines>(
                  __raw__,
                  (a): partial_types.WeatherLines => a,
                  (a): types.WeatherLines => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            SynthesizeMemory(
            query: string,context: types.MemoryContext,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.MemorySynthesisLines, types.MemorySynthesisLines>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for SynthesizeMemory", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const __raw__ = this.runtime.streamFunction(
                "SynthesizeMemory",
                {
                "query": query,"context": context
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __options__.clientRegistry,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.MemorySynthesisLines, types.MemorySynthesisLines>(
                  __raw__,
                  (a): partial_types.MemorySynthesisLines => a,
                  (a): types.MemorySynthesisLines => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
                  }

                  export const b = new BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
                  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)