/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video } from "@boundaryml/baml"
import { toBamlError, HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {AlertLite, AnswerLines, ChatContext, ChatConversationMessage, ChatInterpretation, ChatSessionSummary, ConversationMessage, CurrentLite, DailyForecastItem, DailySummaryResult, EmailContext, EmailInterpretation, EnhancedQuery, FollowupChatContext, FollowupChatResponse, FollowupConversationMessage, FollowupMemoryContext, FollowupSearchResult, FollowupTopic, FormattedWeather, HintCategory, HintEligibility, HintResult, LocationLite, MemoryContext, MemoryCore, MemorySynthesisLines, NewsItem, NoteContent, PlaceLines, PlaceSuggestion, QueryResult, QuestionAnalysisResponse, Router, RoutingBehavior, SessionInput, SessionSummaryOutput, TempBlock, WeatherConditionLite, WeatherLines} from "./types"
import type TypeBuilder from "./type_builder"
import type * as events from "./events"

type BamlCallOptions<EventsT = never> = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  env?: Record<string, string | undefined>
  events?: EventsT
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AbridgeToNote(
      transcripts: string[],
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AbridgeToNote",
        {
          "transcripts": transcripts
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnswerQuestion(
      text: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnswerQuestion",
        {
          "text": text,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnswerSearch(
      query: string,searchResults: types.NewsItem[],memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnswerSearch",
        {
          "query": query,"searchResults": searchResults,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ClassifyForHint(
      text: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "ClassifyForHint",
        {
          "text": text
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  EnhanceQuery(
      query: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "EnhanceQuery",
        {
          "query": query,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractFollowupTopic(
      userUtterance: string,recentMessages: string[],
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "ExtractFollowupTopic",
        {
          "userUtterance": userUtterance,"recentMessages": recentMessages
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateHint(
      topic: string,userSpeech: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "GenerateHint",
        {
          "topic": topic,"userSpeech": userSpeech,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  InterpretChatMessage(
      userMessage: string,context: types.ChatContext,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "InterpretChatMessage",
        {
          "userMessage": userMessage,"context": context
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  InterpretEmailReply(
      userMessage: string,context: types.EmailContext,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "InterpretEmailReply",
        {
          "userMessage": userMessage,"context": context
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  InterpretFollowupChat(
      userMessage: string,context: types.FollowupChatContext,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "InterpretFollowupChat",
        {
          "userMessage": userMessage,"context": context
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  Route(
      text: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "Route",
        {
          "text": text
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeDailySessions(
      sessions: types.SessionInput[],userProfile?: string | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "SummarizeDailySessions",
        {
          "sessions": sessions,"userProfile": userProfile?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizePlaces(
      query: string,places: types.PlaceSuggestion[],memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "SummarizePlaces",
        {
          "query": query,"places": places,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeSession(
      transcripts: string[],
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "SummarizeSession",
        {
          "transcripts": transcripts
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeWeatherFormatted(
      input: types.FormattedWeather,unit: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "SummarizeWeatherFormatted",
        {
          "input": input,"unit": unit,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SynthesizeMemory(
      query: string,context: types.MemoryContext,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "SynthesizeMemory",
        {
          "query": query,"context": context
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AbridgeToNote(
      transcripts: string[],
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AbridgeToNote",
        {
          "transcripts": transcripts
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnswerQuestion(
      text: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnswerQuestion",
        {
          "text": text,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnswerSearch(
      query: string,searchResults: types.NewsItem[],memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnswerSearch",
        {
          "query": query,"searchResults": searchResults,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ClassifyForHint(
      text: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "ClassifyForHint",
        {
          "text": text
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  EnhanceQuery(
      query: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "EnhanceQuery",
        {
          "query": query,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractFollowupTopic(
      userUtterance: string,recentMessages: string[],
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "ExtractFollowupTopic",
        {
          "userUtterance": userUtterance,"recentMessages": recentMessages
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateHint(
      topic: string,userSpeech: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "GenerateHint",
        {
          "topic": topic,"userSpeech": userSpeech,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  InterpretChatMessage(
      userMessage: string,context: types.ChatContext,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "InterpretChatMessage",
        {
          "userMessage": userMessage,"context": context
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  InterpretEmailReply(
      userMessage: string,context: types.EmailContext,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "InterpretEmailReply",
        {
          "userMessage": userMessage,"context": context
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  InterpretFollowupChat(
      userMessage: string,context: types.FollowupChatContext,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "InterpretFollowupChat",
        {
          "userMessage": userMessage,"context": context
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  Route(
      text: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "Route",
        {
          "text": text
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeDailySessions(
      sessions: types.SessionInput[],userProfile?: string | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "SummarizeDailySessions",
        {
          "sessions": sessions,"userProfile": userProfile?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizePlaces(
      query: string,places: types.PlaceSuggestion[],memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "SummarizePlaces",
        {
          "query": query,"places": places,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeSession(
      transcripts: string[],
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "SummarizeSession",
        {
          "transcripts": transcripts
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeWeatherFormatted(
      input: types.FormattedWeather,unit: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "SummarizeWeatherFormatted",
        {
          "input": input,"unit": unit,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SynthesizeMemory(
      query: string,context: types.MemoryContext,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "SynthesizeMemory",
        {
          "query": query,"context": context
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}