/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AlertLite: ClassViewer<'AlertLite', "sender_name" | "event" | "start" | "end" | "description" | "tags">;
    
    AnswerLines: ClassViewer<'AnswerLines', "lines">;
    
    ChatContext: ClassViewer<'ChatContext', "date" | "sessionSummaries" | "userName" | "userFacts" | "deductiveFacts" | "conversationHistory">;
    
    ChatConversationMessage: ClassViewer<'ChatConversationMessage', "role" | "content" | "createdAt">;
    
    ChatInterpretation: ClassViewer<'ChatInterpretation', "response" | "extractedFacts" | "newTopics" | "shouldUpdateSummary" | "summaryAddition">;
    
    ChatSessionSummary: ClassViewer<'ChatSessionSummary', "summary" | "topics" | "startedAt" | "endedAt">;
    
    ConversationMessage: ClassViewer<'ConversationMessage', "direction" | "content">;
    
    CurrentLite: ClassViewer<'CurrentLite', "temperature" | "feels_like" | "conditions" | "humidity" | "pressure" | "wind_speed" | "wind_direction" | "visibility" | "uv_index" | "clouds">;
    
    DailyForecastItem: ClassViewer<'DailyForecastItem', "date" | "summary" | "temperature" | "conditions" | "precipitation_probability" | "rain">;
    
    DailySummaryResult: ClassViewer<'DailySummaryResult', "summary">;
    
    EmailContext: ClassViewer<'EmailContext', "originalSubject" | "sessionSummary" | "sessionTopics" | "peerCard" | "conversationHistory">;
    
    EmailInterpretation: ClassViewer<'EmailInterpretation', "response" | "extractedFacts" | "newTopics" | "shouldUpdateSummary" | "summaryAddition">;
    
    EnhancedQuery: ClassViewer<'EnhancedQuery', "original" | "enhanced">;
    
    FollowupChatContext: ClassViewer<'FollowupChatContext', "topic" | "summary" | "sourceMessages" | "conversationHistory" | "memory" | "searchResults">;
    
    FollowupChatResponse: ClassViewer<'FollowupChatResponse', "response" | "extractedFacts">;
    
    FollowupConversationMessage: ClassViewer<'FollowupConversationMessage', "role" | "content" | "createdAt">;
    
    FollowupMemoryContext: ClassViewer<'FollowupMemoryContext', "userName" | "userFacts" | "deductiveFacts">;
    
    FollowupSearchResult: ClassViewer<'FollowupSearchResult', "title" | "content" | "url">;
    
    FollowupTopic: ClassViewer<'FollowupTopic', "topic" | "summary">;
    
    FormattedWeather: ClassViewer<'FormattedWeather', "location" | "current" | "daily_forecast" | "alerts">;
    
    HintEligibility: ClassViewer<'HintEligibility', "category" | "topic">;
    
    HintResult: ClassViewer<'HintResult', "should_show" | "hint">;
    
    LocationLite: ClassViewer<'LocationLite', "lat" | "lon" | "timezone">;
    
    MemoryContext: ClassViewer<'MemoryContext', "explicitFacts" | "deductiveFacts" | "peerCard" | "recentMessages" | "sessionSummaries" | "crossPeerPerspectives">;
    
    MemoryCore: ClassViewer<'MemoryCore', "userName" | "userFacts" | "deductiveFacts">;
    
    MemorySynthesisLines: ClassViewer<'MemorySynthesisLines', "lines">;
    
    NewsItem: ClassViewer<'NewsItem', "title" | "content">;
    
    NoteContent: ClassViewer<'NoteContent', "title" | "summary" | "keyPoints">;
    
    PlaceLines: ClassViewer<'PlaceLines', "lines">;
    
    PlaceSuggestion: ClassViewer<'PlaceSuggestion', "id" | "name" | "address" | "snippet">;
    
    QueryResult: ClassViewer<'QueryResult', "query" | "results">;
    
    QuestionAnalysisResponse: ClassViewer<'QuestionAnalysisResponse', "original_text" | "has_question" | "question" | "answer">;
    
    RoutingBehavior: ClassViewer<'RoutingBehavior', "origin" | "routing">;
    
    SessionInput: ClassViewer<'SessionInput', "index" | "summary">;
    
    SessionSummaryOutput: ClassViewer<'SessionSummaryOutput', "summary" | "topics">;
    
    TempBlock: ClassViewer<'TempBlock', "day" | "min" | "max" | "night">;
    
    WeatherConditionLite: ClassViewer<'WeatherConditionLite', "id" | "main" | "description" | "icon">;
    
    WeatherLines: ClassViewer<'WeatherLines', "lines">;
    
    
    HintCategory: EnumViewer<'HintCategory', "HINTABLE" | "AMBIENT">;
    
    Router: EnumViewer<'Router', "WEATHER" | "WEB_SEARCH" | "MAPS" | "KNOWLEDGE" | "MEMORY_CAPTURE" | "MEMORY_RECALL" | "NOTE_THIS" | "FOLLOW_UP" | "PASSTHROUGH">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AlertLite","AnswerLines","ChatContext","ChatConversationMessage","ChatInterpretation","ChatSessionSummary","ConversationMessage","CurrentLite","DailyForecastItem","DailySummaryResult","EmailContext","EmailInterpretation","EnhancedQuery","FollowupChatContext","FollowupChatResponse","FollowupConversationMessage","FollowupMemoryContext","FollowupSearchResult","FollowupTopic","FormattedWeather","HintEligibility","HintResult","LocationLite","MemoryContext","MemoryCore","MemorySynthesisLines","NewsItem","NoteContent","PlaceLines","PlaceSuggestion","QueryResult","QuestionAnalysisResponse","RoutingBehavior","SessionInput","SessionSummaryOutput","TempBlock","WeatherConditionLite","WeatherLines",
          ]),
          enums: new Set([
            "HintCategory","Router",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AlertLite = this.tb.classViewer("AlertLite", [
          "sender_name","event","start","end","description","tags",
        ]);
        
        this.AnswerLines = this.tb.classViewer("AnswerLines", [
          "lines",
        ]);
        
        this.ChatContext = this.tb.classViewer("ChatContext", [
          "date","sessionSummaries","userName","userFacts","deductiveFacts","conversationHistory",
        ]);
        
        this.ChatConversationMessage = this.tb.classViewer("ChatConversationMessage", [
          "role","content","createdAt",
        ]);
        
        this.ChatInterpretation = this.tb.classViewer("ChatInterpretation", [
          "response","extractedFacts","newTopics","shouldUpdateSummary","summaryAddition",
        ]);
        
        this.ChatSessionSummary = this.tb.classViewer("ChatSessionSummary", [
          "summary","topics","startedAt","endedAt",
        ]);
        
        this.ConversationMessage = this.tb.classViewer("ConversationMessage", [
          "direction","content",
        ]);
        
        this.CurrentLite = this.tb.classViewer("CurrentLite", [
          "temperature","feels_like","conditions","humidity","pressure","wind_speed","wind_direction","visibility","uv_index","clouds",
        ]);
        
        this.DailyForecastItem = this.tb.classViewer("DailyForecastItem", [
          "date","summary","temperature","conditions","precipitation_probability","rain",
        ]);
        
        this.DailySummaryResult = this.tb.classViewer("DailySummaryResult", [
          "summary",
        ]);
        
        this.EmailContext = this.tb.classViewer("EmailContext", [
          "originalSubject","sessionSummary","sessionTopics","peerCard","conversationHistory",
        ]);
        
        this.EmailInterpretation = this.tb.classViewer("EmailInterpretation", [
          "response","extractedFacts","newTopics","shouldUpdateSummary","summaryAddition",
        ]);
        
        this.EnhancedQuery = this.tb.classViewer("EnhancedQuery", [
          "original","enhanced",
        ]);
        
        this.FollowupChatContext = this.tb.classViewer("FollowupChatContext", [
          "topic","summary","sourceMessages","conversationHistory","memory","searchResults",
        ]);
        
        this.FollowupChatResponse = this.tb.classViewer("FollowupChatResponse", [
          "response","extractedFacts",
        ]);
        
        this.FollowupConversationMessage = this.tb.classViewer("FollowupConversationMessage", [
          "role","content","createdAt",
        ]);
        
        this.FollowupMemoryContext = this.tb.classViewer("FollowupMemoryContext", [
          "userName","userFacts","deductiveFacts",
        ]);
        
        this.FollowupSearchResult = this.tb.classViewer("FollowupSearchResult", [
          "title","content","url",
        ]);
        
        this.FollowupTopic = this.tb.classViewer("FollowupTopic", [
          "topic","summary",
        ]);
        
        this.FormattedWeather = this.tb.classViewer("FormattedWeather", [
          "location","current","daily_forecast","alerts",
        ]);
        
        this.HintEligibility = this.tb.classViewer("HintEligibility", [
          "category","topic",
        ]);
        
        this.HintResult = this.tb.classViewer("HintResult", [
          "should_show","hint",
        ]);
        
        this.LocationLite = this.tb.classViewer("LocationLite", [
          "lat","lon","timezone",
        ]);
        
        this.MemoryContext = this.tb.classViewer("MemoryContext", [
          "explicitFacts","deductiveFacts","peerCard","recentMessages","sessionSummaries","crossPeerPerspectives",
        ]);
        
        this.MemoryCore = this.tb.classViewer("MemoryCore", [
          "userName","userFacts","deductiveFacts",
        ]);
        
        this.MemorySynthesisLines = this.tb.classViewer("MemorySynthesisLines", [
          "lines",
        ]);
        
        this.NewsItem = this.tb.classViewer("NewsItem", [
          "title","content",
        ]);
        
        this.NoteContent = this.tb.classViewer("NoteContent", [
          "title","summary","keyPoints",
        ]);
        
        this.PlaceLines = this.tb.classViewer("PlaceLines", [
          "lines",
        ]);
        
        this.PlaceSuggestion = this.tb.classViewer("PlaceSuggestion", [
          "id","name","address","snippet",
        ]);
        
        this.QueryResult = this.tb.classViewer("QueryResult", [
          "query","results",
        ]);
        
        this.QuestionAnalysisResponse = this.tb.classViewer("QuestionAnalysisResponse", [
          "original_text","has_question","question","answer",
        ]);
        
        this.RoutingBehavior = this.tb.classViewer("RoutingBehavior", [
          "origin","routing",
        ]);
        
        this.SessionInput = this.tb.classViewer("SessionInput", [
          "index","summary",
        ]);
        
        this.SessionSummaryOutput = this.tb.classViewer("SessionSummaryOutput", [
          "summary","topics",
        ]);
        
        this.TempBlock = this.tb.classViewer("TempBlock", [
          "day","min","max","night",
        ]);
        
        this.WeatherConditionLite = this.tb.classViewer("WeatherConditionLite", [
          "id","main","description","icon",
        ]);
        
        this.WeatherLines = this.tb.classViewer("WeatherLines", [
          "lines",
        ]);
        
        
        this.HintCategory = this.tb.enumViewer("HintCategory", [
          "HINTABLE","AMBIENT",
        ]);
        
        this.Router = this.tb.enumViewer("Router", [
          "WEATHER","WEB_SEARCH","MAPS","KNOWLEDGE","MEMORY_CAPTURE","MEMORY_RECALL","NOTE_THIS","FOLLOW_UP","PASSTHROUGH",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}