/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AlertLite,  AnswerLines,  CurrentLite,  DailyForecastItem,  FormattedWeather,  LocationLite,  MemoryRecall,  NewsItem,  PlaceLines,  PlaceSuggestion,  QueryResult,  QuestionAnalysisResponse,  Router,  RoutingBehavior,  TempBlock,  WeatherConditionLite,  WeatherLines } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AlertLite {
      sender_name?: string | null
      event?: string | null
      start?: number | null
      end?: number | null
      description?: string | null
      tags: string[]
    }
    export interface AnswerLines {
      lines: string[]
    }
    export interface CurrentLite {
      temperature?: number | null
      feels_like?: number | null
      conditions?: WeatherConditionLite | null
      humidity?: number | null
      pressure?: number | null
      wind_speed?: number | null
      wind_direction?: number | null
      visibility?: number | null
      uv_index?: number | null
      clouds?: number | null
    }
    export interface DailyForecastItem {
      date?: string | null
      summary?: string | null
      temperature?: TempBlock | null
      conditions?: WeatherConditionLite | null
      precipitation_probability?: number | null
      rain?: number | null
    }
    export interface FormattedWeather {
      location?: LocationLite | null
      current?: CurrentLite | null
      daily_forecast: DailyForecastItem[]
      alerts: AlertLite[]
    }
    export interface LocationLite {
      lat?: number | null
      lon?: number | null
      timezone?: string | null
    }
    export interface MemoryRecall {
      query?: string | null
      results?: AnswerLines | null
    }
    export interface NewsItem {
      title?: string | null
      content?: string | null
    }
    export interface PlaceLines {
      lines: string[]
    }
    export interface PlaceSuggestion {
      id?: string | null
      name?: string | null
      address?: string | null
      snippet?: string | null
    }
    export interface QueryResult {
      query?: string | null
      results: AnswerLines[]
    }
    export interface QuestionAnalysisResponse {
      original_text?: string | null
      has_question?: boolean | null
      question?: string | null
      answer: string[]
    }
    export interface RoutingBehavior {
      origin?: string | null
      routing?: types.Router | null
    }
    export interface TempBlock {
      day?: number | null
      min?: number | null
      max?: number | null
      night?: number | null
    }
    export interface WeatherConditionLite {
      id?: number | null
      main?: string | null
      description?: string | null
      icon?: string | null
    }
    export interface WeatherLines {
      lines: string[]
    }
}