/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum Router {
  WEATHER = "WEATHER",
  WEB_SEARCH = "WEB_SEARCH",
  MAPS = "MAPS",
  KNOWLEDGE = "KNOWLEDGE",
  MEMORY_RECALL = "MEMORY_RECALL",
}

export interface AlertLite {
  sender_name: string
  event: string
  start: number
  end: number
  description: string
  tags: string[]
  
}

export interface AnswerLines {
  lines: string[]
  
}

export interface CurrentLite {
  temperature: number
  feels_like: number
  conditions: WeatherConditionLite
  humidity: number
  pressure: number
  wind_speed: number
  wind_direction: number
  visibility: number
  uv_index: number
  clouds: number
  
}

export interface DailyForecastItem {
  date: string
  summary: string
  temperature: TempBlock
  conditions: WeatherConditionLite
  precipitation_probability: number
  rain: number
  
}

export interface FormattedWeather {
  location: LocationLite
  current: CurrentLite
  daily_forecast: DailyForecastItem[]
  alerts: AlertLite[]
  
}

export interface LocationLite {
  lat: number
  lon: number
  timezone: string
  
}

export interface MemoryRecall {
  query: string
  results: AnswerLines
  
}

export interface NewsItem {
  title: string
  content: string
  
}

export interface PlaceLines {
  lines: string[]
  
}

export interface PlaceSuggestion {
  id: string
  name: string
  address: string
  snippet?: string | null
  
}

export interface QueryResult {
  query: string
  results: AnswerLines[]
  
}

export interface QuestionAnalysisResponse {
  original_text: string
  has_question: boolean
  question?: string | null
  answer: string[]
  
}

export interface RoutingBehavior {
  origin: string
  routing: Router
  
}

export interface TempBlock {
  day: number
  min: number
  max: number
  night: number
  
}

export interface WeatherConditionLite {
  id: number
  main: string
  description: string
  icon: string
  
}

export interface WeatherLines {
  lines: string[]
  
}
