/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video, FunctionLog } from
"@boundaryml/baml"
import { toBamlError, HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {AlertLite, AnswerLines, CurrentLite, DailyForecastItem, EnhancedQuery, FormattedWeather, HintCategory, HintEligibility, HintResult, LocationLite, MemoryContext, MemoryCore, MemorySynthesisLines, NewsItem, PlaceLines, PlaceSuggestion, QueryResult, QuestionAnalysisResponse, Router, RoutingBehavior, SessionSummaryOutput, TempBlock, WeatherConditionLite, WeatherLines} from "./types"
import type TypeBuilder from "./type_builder"
import type * as events from "./events"

type TickReason = "Unknown";

type BamlCallOptions<EventsT = never> = {
tb?: TypeBuilder
clientRegistry?: ClientRegistry
env?: Record<string, string | undefined>
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  events?: EventsT
  }

  export class AsyncHttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  async AnswerQuestion(
  text: string,memory?: types.MemoryCore | null,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return await this.runtime.buildRequest(
      "AnswerQuestion",
      {
      "text": text,"memory": memory?? null
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async AnswerSearch(
  query: string,searchResults: types.NewsItem[],memory?: types.MemoryCore | null,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return await this.runtime.buildRequest(
      "AnswerSearch",
      {
      "query": query,"searchResults": searchResults,"memory": memory?? null
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ClassifyForHint(
  text: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return await this.runtime.buildRequest(
      "ClassifyForHint",
      {
      "text": text
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async EnhanceQuery(
  query: string,memory?: types.MemoryCore | null,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return await this.runtime.buildRequest(
      "EnhanceQuery",
      {
      "query": query,"memory": memory?? null
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async GenerateHint(
  topic: string,userSpeech: string,memory?: types.MemoryCore | null,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return await this.runtime.buildRequest(
      "GenerateHint",
      {
      "topic": topic,"userSpeech": userSpeech,"memory": memory?? null
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async Route(
  text: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return await this.runtime.buildRequest(
      "Route",
      {
      "text": text
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async SummarizePlaces(
  query: string,places: types.PlaceSuggestion[],memory?: types.MemoryCore | null,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return await this.runtime.buildRequest(
      "SummarizePlaces",
      {
      "query": query,"places": places,"memory": memory?? null
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async SummarizeSession(
  transcripts: string[],
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return await this.runtime.buildRequest(
      "SummarizeSession",
      {
      "transcripts": transcripts
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async SummarizeWeatherFormatted(
  input: types.FormattedWeather,unit: string,memory?: types.MemoryCore | null,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return await this.runtime.buildRequest(
      "SummarizeWeatherFormatted",
      {
      "input": input,"unit": unit,"memory": memory?? null
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async SynthesizeMemory(
  query: string,context: types.MemoryContext,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return await this.runtime.buildRequest(
      "SynthesizeMemory",
      {
      "query": query,"context": context
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
      }

      export class AsyncHttpStreamRequest {
      constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

      
      async AnswerQuestion(
      text: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );
          return await this.runtime.buildRequest(
          "AnswerQuestion",
          {
          "text": text,"memory": memory?? null
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __baml_options__?.clientRegistry,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async AnswerSearch(
      query: string,searchResults: types.NewsItem[],memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );
          return await this.runtime.buildRequest(
          "AnswerSearch",
          {
          "query": query,"searchResults": searchResults,"memory": memory?? null
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __baml_options__?.clientRegistry,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ClassifyForHint(
      text: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );
          return await this.runtime.buildRequest(
          "ClassifyForHint",
          {
          "text": text
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __baml_options__?.clientRegistry,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async EnhanceQuery(
      query: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );
          return await this.runtime.buildRequest(
          "EnhanceQuery",
          {
          "query": query,"memory": memory?? null
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __baml_options__?.clientRegistry,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async GenerateHint(
      topic: string,userSpeech: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );
          return await this.runtime.buildRequest(
          "GenerateHint",
          {
          "topic": topic,"userSpeech": userSpeech,"memory": memory?? null
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __baml_options__?.clientRegistry,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async Route(
      text: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );
          return await this.runtime.buildRequest(
          "Route",
          {
          "text": text
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __baml_options__?.clientRegistry,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async SummarizePlaces(
      query: string,places: types.PlaceSuggestion[],memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );
          return await this.runtime.buildRequest(
          "SummarizePlaces",
          {
          "query": query,"places": places,"memory": memory?? null
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __baml_options__?.clientRegistry,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async SummarizeSession(
      transcripts: string[],
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );
          return await this.runtime.buildRequest(
          "SummarizeSession",
          {
          "transcripts": transcripts
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __baml_options__?.clientRegistry,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async SummarizeWeatherFormatted(
      input: types.FormattedWeather,unit: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );
          return await this.runtime.buildRequest(
          "SummarizeWeatherFormatted",
          {
          "input": input,"unit": unit,"memory": memory?? null
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __baml_options__?.clientRegistry,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async SynthesizeMemory(
      query: string,context: types.MemoryContext,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );
          return await this.runtime.buildRequest(
          "SynthesizeMemory",
          {
          "query": query,"context": context
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __baml_options__?.clientRegistry,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
          }