/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, Image, Audio, Pdf, Video, ClientRegistry, Collector, FunctionLog } from "@boundaryml/baml"
import { toBamlError, BamlAbortError, type HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type * as types from "./types"
import type {AlertLite, AnswerLines, CurrentLite, DailyForecastItem, EnhancedQuery, FormattedWeather, LocationLite, MemoryContext, MemoryCore, MemoryRecall, MemorySynthesisLines, NewsItem, PlaceLines, PlaceSuggestion, QueryResult, QuestionAnalysisResponse, Router, RoutingBehavior, TempBlock, WeatherConditionLite, WeatherLines} from "./types"
import type TypeBuilder from "./type_builder"
import { HttpRequest, HttpStreamRequest } from "./sync_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"
import type * as events from "./events"

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 * Example:
 * ```ts
 * import { RecursivePartialNull } from './baml_client/types'
 * ```
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>;

type TickReason = "Unknown";

type BamlCallOptions<WatchersT = never> = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  collector?: Collector | Collector[]
  env?: Record<string, string | undefined>
  tags?: Record<string, string>
  signal?: AbortSignal
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  watchers?: WatchersT
}

export class BamlSyncClient {
  private httpRequest: HttpRequest
  private httpStreamRequest: HttpStreamRequest
  private llmResponseParser: LlmResponseParser
  private llmStreamParser: LlmStreamParser
  private bamlOptions: BamlCallOptions

  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
    this.httpRequest = new HttpRequest(runtime, ctxManager)
    this.httpStreamRequest = new HttpStreamRequest(runtime, ctxManager)
    this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
    this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
    this.bamlOptions = bamlOptions || {}
  }

  withOptions(bamlOptions: BamlCallOptions) {
    return new BamlSyncClient(this.runtime, this.ctxManager, bamlOptions)
  }

  /*
  * @deprecated NOT IMPLEMENTED as streaming must by async. We
  * are not providing an async version as we want to reserve the
  * right to provide a sync version in the future.
  */
  get stream() {
    throw new Error("stream is not available in BamlSyncClient. Use `import { b } from 'baml_client/async_client")
  }

  get request() {
    return this.httpRequest
  }

  get streamRequest() {
    return this.httpStreamRequest
  }

  get parse() {
    return this.llmResponseParser
  }

  get parseStream() {
    return this.llmStreamParser
  }

  
  AnswerQuestion(
      text: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.QuestionAnalysisResponse {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      const __raw__ = this.runtime.callFunctionSync(
        "AnswerQuestion",
        {
          "text": text,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __options__.clientRegistry,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.QuestionAnalysisResponse
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  AnswerSearch(
      query: string,searchResults: types.NewsItem[],memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.QueryResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      const __raw__ = this.runtime.callFunctionSync(
        "AnswerSearch",
        {
          "query": query,"searchResults": searchResults,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __options__.clientRegistry,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.QueryResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  EnhanceQuery(
      query: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.EnhancedQuery {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      const __raw__ = this.runtime.callFunctionSync(
        "EnhanceQuery",
        {
          "query": query,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __options__.clientRegistry,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.EnhancedQuery
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  MemoryQueryRecall(
      query: string,context: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.MemoryRecall {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      const __raw__ = this.runtime.callFunctionSync(
        "MemoryQueryRecall",
        {
          "query": query,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __options__.clientRegistry,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.MemoryRecall
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  Route(
      text: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.RoutingBehavior {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      const __raw__ = this.runtime.callFunctionSync(
        "Route",
        {
          "text": text
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __options__.clientRegistry,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.RoutingBehavior
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  SummarizePlaces(
      query: string,places: types.PlaceSuggestion[],memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.PlaceLines {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      const __raw__ = this.runtime.callFunctionSync(
        "SummarizePlaces",
        {
          "query": query,"places": places,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __options__.clientRegistry,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.PlaceLines
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  SummarizeWeatherFormatted(
      input: types.FormattedWeather,unit: string,memory?: types.MemoryCore | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.WeatherLines {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      const __raw__ = this.runtime.callFunctionSync(
        "SummarizeWeatherFormatted",
        {
          "input": input,"unit": unit,"memory": memory?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __options__.clientRegistry,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.WeatherLines
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  SynthesizeMemory(
      query: string,context: types.MemoryContext,
      __baml_options__?: BamlCallOptions<never>
  ): types.MemorySynthesisLines {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      const __raw__ = this.runtime.callFunctionSync(
        "SynthesizeMemory",
        {
          "query": query,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __options__.clientRegistry,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.MemorySynthesisLines
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
}

export const b = new BamlSyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)